### ISSUE TITLE
Create database with users .

### ISSUE THREAD

**Issue by lucianperju** [asaltvld30/ForumTestApp#1]
User should be like : 
                                 Name
                                 Short Name
                                 Posts
                                 Rating
                                 Warnings / Ban
                                 Badges
                                 Friends
                                 Private rooms
                                 Avatar(Profile pic)

**Comment by asaltvld30** [comment]
Create User table, then Profile table
User
ID, username, password
Profile
ID, Name, Nickname, Rating, etc. user_ID
